-- =============================================================================
-- CARTHAGO DATABASE SCHEMA
-- =============================================================================
-- Script pour créer les tables nécessaires au traitement des fichiers Carthago
-- et à la comparaison avec les fichiers Encaisse Valeur

-- =============================================================================
-- 1. Table CARTHAGO - Stocke les fichiers Carthago bruts (.DATA)
-- =============================================================================
CREATE TABLE CARTHAGO (
    ID            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOM_FICHIER   VARCHAR2(255 CHAR), -- nom du fichier Carthago
    DATE_IMPORT   DATE DEFAULT SYSDATE,
    CONTENU       CLOB,               -- contenu brut
    CREATED_AT    DATE DEFAULT SYSDATE
);

-- =============================================================================
-- 2. Table CARTHAGO_DETAIL - Stocke chaque chèque issu du parsing de CARTHAGO
-- =============================================================================
CREATE TABLE CARTHAGO_DETAIL (
    ID               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CARTHAGO_ID      NUMBER(19) REFERENCES CARTHAGO(ID) ON DELETE CASCADE,
    NUMERO_CHEQUE    VARCHAR2(50 CHAR),  -- numéro du chèque si présent
    MONTANT_CHEQUE   NUMBER(15,2),
    ETAT_CHEQUE      VARCHAR2(10 CHAR),  -- 'DEPOSE' ou 'REJETE'
    LIGNE_ORIGINE    VARCHAR2(500 CHAR)  -- ligne brute du fichier
);

-- =============================================================================
-- 3. Table CTR - Stocke le résultat de la comparaison entre Encaisse Valeur et Carthago
-- =============================================================================
CREATE TABLE CTR (
    ID                       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FICHIER_ID               NUMBER(19) REFERENCES FICHIERS(ID_FICHIER),
    CARTHAGO_ID              NUMBER(19) REFERENCES CARTHAGO(ID),

    -- Données Carthago
    NOMBRE_TOTAL_CARTHAGO    NUMBER(10),
    MONTANT_TOTAL_CARTHAGO   NUMBER(15,2),
    NOMBRE_DEP_CARTHAGO      NUMBER(10),    -- chèques déposés
    MONTANT_DEP_CARTHAGO     NUMBER(15,2),
    NOMBRE_REJ_CARTHAGO      NUMBER(10),    -- chèques rejetés
    MONTANT_REJ_CARTHAGO     NUMBER(15,2),

    -- Données Encaisse Valeur (FICHIERS)
    NOMBRE_FICHIER           NUMBER(10),
    MONTANT_FICHIER          NUMBER(15,2),

    -- Résultat comparaison
    NOMBRE_OK                CHAR(1),       -- 'Y' ou 'N'
    MONTANT_OK               CHAR(1),       -- 'Y' ou 'N'

    CREATED_AT               DATE DEFAULT SYSDATE
);

-- =============================================================================
-- INDEXES POUR OPTIMISER LES PERFORMANCES
-- =============================================================================

-- Index sur les clés étrangères
CREATE INDEX IDX_CARTHAGO_DETAIL_CARTHAGO_ID ON CARTHAGO_DETAIL(CARTHAGO_ID);
CREATE INDEX IDX_CTR_FICHIER_ID ON CTR(FICHIER_ID);
CREATE INDEX IDX_CTR_CARTHAGO_ID ON CTR(CARTHAGO_ID);

-- Index sur les colonnes fréquemment utilisées pour les recherches
CREATE INDEX IDX_CARTHAGO_NOM_FICHIER ON CARTHAGO(NOM_FICHIER);
CREATE INDEX IDX_CARTHAGO_DATE_IMPORT ON CARTHAGO(DATE_IMPORT);
CREATE INDEX IDX_CARTHAGO_DETAIL_ETAT ON CARTHAGO_DETAIL(ETAT_CHEQUE);
CREATE INDEX IDX_CTR_CREATED_AT ON CTR(CREATED_AT);

-- =============================================================================
-- COMMENTAIRES POUR DOCUMENTATION
-- =============================================================================

COMMENT ON TABLE CARTHAGO IS 'Stocke les fichiers Carthago bruts (.DATA) avant parsing';
COMMENT ON TABLE CARTHAGO_DETAIL IS 'Stocke chaque chèque issu du parsing de CARTHAGO';
COMMENT ON TABLE CTR IS 'Stocke le résultat de la comparaison entre Encaisse Valeur et Carthago';

COMMENT ON COLUMN CARTHAGO.ID IS 'Identifiant unique auto-généré';
COMMENT ON COLUMN CARTHAGO.NOM_FICHIER IS 'Nom original du fichier Carthago';
COMMENT ON COLUMN CARTHAGO.DATE_IMPORT IS 'Date d''import du fichier';
COMMENT ON COLUMN CARTHAGO.CONTENU IS 'Contenu brut du fichier (.DATA)';

COMMENT ON COLUMN CARTHAGO_DETAIL.ID IS 'Identifiant unique auto-généré';
COMMENT ON COLUMN CARTHAGO_DETAIL.CARTHAGO_ID IS 'Référence vers le fichier Carthago parent';
COMMENT ON COLUMN CARTHAGO_DETAIL.NUMERO_CHEQUE IS 'Numéro du chèque si présent dans le fichier';
COMMENT ON COLUMN CARTHAGO_DETAIL.MONTANT_CHEQUE IS 'Montant du chèque';
COMMENT ON COLUMN CARTHAGO_DETAIL.ETAT_CHEQUE IS 'État du chèque: DEPOSE ou REJETE';
COMMENT ON COLUMN CARTHAGO_DETAIL.LIGNE_ORIGINE IS 'Ligne brute du fichier source';

COMMENT ON COLUMN CTR.ID IS 'Identifiant unique auto-généré';
COMMENT ON COLUMN CTR.FICHIER_ID IS 'Référence vers le fichier Encaisse Valeur';
COMMENT ON COLUMN CTR.CARTHAGO_ID IS 'Référence vers le fichier Carthago';
COMMENT ON COLUMN CTR.NOMBRE_TOTAL_CARTHAGO IS 'Nombre total de chèques dans Carthago';
COMMENT ON COLUMN CTR.MONTANT_TOTAL_CARTHAGO IS 'Montant total des chèques dans Carthago';
COMMENT ON COLUMN CTR.NOMBRE_DEP_CARTHAGO IS 'Nombre de chèques déposés dans Carthago';
COMMENT ON COLUMN CTR.MONTANT_DEP_CARTHAGO IS 'Montant total des chèques déposés';
COMMENT ON COLUMN CTR.NOMBRE_REJ_CARTHAGO IS 'Nombre de chèques rejetés dans Carthago';
COMMENT ON COLUMN CTR.MONTANT_REJ_CARTHAGO IS 'Montant total des chèques rejetés';
COMMENT ON COLUMN CTR.NOMBRE_FICHIER IS 'Nombre de chèques dans le fichier Encaisse Valeur';
COMMENT ON COLUMN CTR.MONTANT_FICHIER IS 'Montant total dans le fichier Encaisse Valeur';
COMMENT ON COLUMN CTR.NOMBRE_OK IS 'Correspondance du nombre: Y ou N';
COMMENT ON COLUMN CTR.MONTANT_OK IS 'Correspondance du montant: Y ou N';

-- =============================================================================
-- VUES UTILES POUR LE DASHBOARD
-- =============================================================================

-- Vue pour résumé des fichiers Carthago
CREATE OR REPLACE VIEW V_CARTHAGO_SUMMARY AS
SELECT 
    c.ID,
    c.NOM_FICHIER,
    c.DATE_IMPORT,
    COUNT(cd.ID) as NOMBRE_TOTAL_CHEQUES,
    SUM(cd.MONTANT_CHEQUE) as MONTANT_TOTAL,
    COUNT(CASE WHEN cd.ETAT_CHEQUE = 'DEPOSE' THEN 1 END) as NOMBRE_DEPOSES,
    SUM(CASE WHEN cd.ETAT_CHEQUE = 'DEPOSE' THEN cd.MONTANT_CHEQUE ELSE 0 END) as MONTANT_DEPOSES,
    COUNT(CASE WHEN cd.ETAT_CHEQUE = 'REJETE' THEN 1 END) as NOMBRE_REJETES,
    SUM(CASE WHEN cd.ETAT_CHEQUE = 'REJETE' THEN cd.MONTANT_CHEQUE ELSE 0 END) as MONTANT_REJETES
FROM CARTHAGO c
LEFT JOIN CARTHAGO_DETAIL cd ON c.ID = cd.CARTHAGO_ID
GROUP BY c.ID, c.NOM_FICHIER, c.DATE_IMPORT;

-- Vue pour comparaison CTR
CREATE OR REPLACE VIEW V_CTR_COMPARISON AS
SELECT 
    ctr.ID,
    f.NOM_FICHIER as FICHIER_NOM,
    car.NOM_FICHIER as CARTHAGO_NOM,
    ctr.NOMBRE_FICHIER,
    ctr.MONTANT_FICHIER,
    ctr.NOMBRE_TOTAL_CARTHAGO,
    ctr.MONTANT_TOTAL_CARTHAGO,
    ctr.NOMBRE_OK,
    ctr.MONTANT_OK,
    ctr.CREATED_AT
FROM CTR ctr
JOIN FICHIERS f ON ctr.FICHIER_ID = f.ID_FICHIER
JOIN CARTHAGO car ON ctr.CARTHAGO_ID = car.ID;

-- =============================================================================
-- SCRIPT TERMINÉ
-- ============================================================================= 